trigger:
- master

pool:
  name: AgentDonalda

variables:
  buildConfiguration: 'Release'
  sonar.projectKey: 'DevOps-Group4'
  sonar.projectName: 'DevOps-Group4'
  sonar.organization: 'donaldazhuga'

stages:
# ------------------------------
# CI - BUILD & TEST
# ------------------------------
- stage: Build
  displayName: 'Build and Test'
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
  jobs:
    - job: Build
      steps:
        # Step 1: Checkout code from the repository
        - checkout: self
          clean: true

        # Step 2: Maven Build and Test with Java 21
        - task: Maven@3
          displayName: 'Maven Build and Test'
          inputs:
            mavenPomFile: 'pom.xml'
            goals: 'clean verify'
            options: '-DskipTests=false -Dsonar.skip=true'
            javaHomeOption: 'JDKVersion'
            jdkVersionOption: '21'
            mavenVersionOption: 'Default'
            publishJUnitResults: true
            testResultsFiles: '**/surefire-reports/TEST-*.xml'
            mavenAuthenticateFeed: true

        # Step 3: SonarCloud Analysis
        - task: SonarCloudPrepare@1
          displayName: 'Prepare SonarCloud Analysis'
          inputs:
            SonarCloud: 'DevOps'
            organization: '$(sonar.organization)'
            scannerMode: 'MSBuild'
            projectKey: '$(sonar.projectKey)'
            projectName: '$(sonar.projectName)'
            extraProperties: |
              sonar.verbose=true
              sonar.java.source=21
              sonar.java.target=21
              sonar.sourceEncoding=UTF-8
              sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
              sonar.junit.reportPaths=target/surefire-reports

        - task: SonarCloudAnalyze@1
          displayName: 'Run SonarCloud Analysis'
          timeoutInMinutes: 10

        - task: SonarCloudPublish@1
          displayName: 'Publish SonarCloud Results'
          inputs:
            pollingTimeoutSec: '300'

        # Step 4: Publish Build Artifacts
        - task: PublishBuildArtifacts@1
          displayName: 'Publish Artifacts'
          inputs:
            PathtoPublish: 'target'
            ArtifactName: 'drop'
            publishLocation: 'Container'

# ------------------------------
# CD - DEPLOYMENT
# ------------------------------
- stage: Deliver
  displayName: 'Deliver Artifacts'
  dependsOn: Build
  condition: succeeded()
  jobs:
    - job: Deliver
      steps:
        - download: current
          artifact: drop
          displayName: 'Download Artifacts'

        - script: echo "Delivering artifact to next stage"
          displayName: 'Mock Deliver Step'

- stage: DeployToDev
  displayName: 'Deploy to Dev Environment'
  dependsOn: Deliver
  condition: succeeded()
  jobs:
    - job: DeployDev
      steps:
        - script: |
            echo "Starting Dev Deployment"
            java -jar target/*.jar --server.port=8081
          displayName: 'Deploy to Dev Port 8081'
          env:
            JAVA_HOME: $(JAVA_HOME_21_X64)

- stage: DeployToQAT
  displayName: 'Deploy to QAT Environment'
  dependsOn: [DeployToDev]
  condition: succeeded()
  jobs:
    - job: DeployQAT
      steps:
        - script: echo "Mock Deployment to QAT"
          displayName: 'Deploy to QAT'

- stage: DeployToStaging
  displayName: 'Deploy to Staging Environment'
  dependsOn: [DeployToQAT]
  condition: succeeded()
  jobs:
    - job: DeployStaging
      steps:
        - script: echo "Mock Deployment to Staging"
          displayName: 'Deploy to Staging'

- stage: DeployToProduction
  displayName: 'Deploy to Production Environment'
  dependsOn: [DeployToStaging]
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  jobs:
    - job: DeployProd
      steps:
        - script: echo "Mock Deployment to Production"
          displayName: 'Deploy to Production'