trigger:
- master

pool:
  name: AgentDonalda

variables:
  buildConfiguration: 'Release'
  sonar.projectKey: 'DevOps-Group4'
  sonar.projectName: 'DevOps-Group4'
  sonar.organization: 'donaldazhuga'
  mavenVersion: '3.6.3'

stages:
# ------------------------------
# CI - BUILD & TEST
# ------------------------------
- stage: Build
  displayName: 'Build and Test'
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
  jobs:
    - job: Build
      steps:
        # Step 1: Checkout code from the repository
        - checkout: self
          clean: true
          fetchDepth: 1

        # Step 2: Set up Java 21
        - task: JavaToolInstaller@0
          displayName: 'Install Java 21'
          inputs:
            versionSpec: '21'
            jdkArchitectureOption: 'x64'
            jdkSourceOption: 'PreInstalled'

        # Step 3: Maven Build with SonarCloud Analysis
        - task: Maven@3
          displayName: 'Maven Build with Sonar Analysis'
          inputs:
            mavenPomFile: 'pom.xml'
            goals: 'clean verify org.sonarsource.scanner.maven:sonar-maven-plugin:3.11.0.2182:sonar'
            options: >-
              -DskipTests=false
              -Dsonar.projectKey=$(sonar.projectKey)
              -Dsonar.projectName=$(sonar.projectName)
              -Dsonar.organization=$(sonar.organization)
              -Dsonar.host.url=https://sonarcloud.io
              -Dsonar.login=$(SONAR_TOKEN)
              -Dsonar.java.source=21
              -Dsonar.java.target=21
              -Dsonar.sourceEncoding=UTF-8
              -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
              -Dsonar.junit.reportPaths=target/surefire-reports
              -Dsonar.qualitygate.wait=true
            mavenVersionOption: 'Path'
            mavenDirectory: '$(MAVEN_HOME)'
            publishJUnitResults: true
            testResultsFiles: '**/surefire-reports/TEST-*.xml'
            mavenAuthenticateFeed: true
          env:
            SONAR_TOKEN: $(sonarCloudToken) # Secret variable in Azure DevOps

        # Step 4: Publish Build Artifacts
        - task: PublishBuildArtifacts@1
          displayName: 'Publish Artifacts'
          inputs:
            PathtoPublish: 'target'
            ArtifactName: 'drop'
            publishLocation: 'Container'

# ------------------------------
# CD - DEPLOYMENT
# ------------------------------
- stage: Deliver
  displayName: 'Deliver Artifacts'
  dependsOn: Build
  condition: succeeded()
  jobs:
    - job: Deliver
      steps:
        - download: current
          artifact: drop
          displayName: 'Download Artifacts'

        - script: |
            echo "Delivering artifact to next stage"
            ls -R target
          displayName: 'Verify Artifacts'

- stage: DeployToDev
  displayName: 'Deploy to Dev Environment'
  dependsOn: Deliver
  condition: succeeded()
  jobs:
    - job: DeployDev
      steps:
        - download: current
          artifact: drop
          displayName: 'Download Artifacts'
        
        - script: |
            echo "Starting Dev Deployment"
            nohup java -jar target/*.jar --server.port=8081 > app.log 2>&1 &
            echo $! > pid.file
            sleep 30
            cat app.log
          displayName: 'Deploy to Dev Port 8081'
          env:
            JAVA_HOME: $(JAVA_HOME_21_X64)

- stage: DeployToQAT
  displayName: 'Deploy to QA Environment'
  dependsOn: DeployToDev
  condition: succeeded()
  jobs:
    - job: DeployQAT
      steps:
        - download: current
          artifact: drop
          displayName: 'Download Artifacts'
        
        - script: |
            echo "Starting QA Deployment"
            nohup java -jar target/*.jar --server.port=8082 > app.log 2>&1 &
            echo $! > pid.file
            sleep 30
            cat app.log
          displayName: 'Deploy to QA Port 8082'
          env:
            JAVA_HOME: $(JAVA_HOME_21_X64)

- stage: DeployToStaging
  displayName: 'Deploy to Staging Environment'
  dependsOn: DeployToQAT
  condition: succeeded()
  jobs:
    - job: DeployStaging
      steps:
        - download: current
          artifact: drop
          displayName: 'Download Artifacts'
        
        - script: |
            echo "Starting Staging Deployment"
            nohup java -jar target/*.jar --server.port=8083 > app.log 2>&1 &
            echo $! > pid.file
            sleep 30
            cat app.log
          displayName: 'Deploy to Staging Port 8083'
          env:
            JAVA_HOME: $(JAVA_HOME_21_X64)

- stage: DeployToProduction
  displayName: 'Deploy to Production Environment'
  dependsOn: DeployToStaging
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  jobs:
    - job: DeployProd
      steps:
        - download: current
          artifact: drop
          displayName: 'Download Artifacts'
        
        - script: |
            echo "Starting Production Deployment"
            nohup java -jar target/*.jar --server.port=8080 > app.log 2>&1 &
            echo $! > pid.file
            sleep 30
            cat app.log
          displayName: 'Deploy to Production Port 8080'
          env:
            JAVA_HOME: $(JAVA_HOME_21_X64)