trigger:
- master

pool:
  name: AgentDonalda

steps:
# Step 1: SonarCloud Prepare
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'DevOps'   # Your service connection name in Azure DevOps
    organization: 'donaldazhuga'         # Your organization name in SonarCloud
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: 'donaldazhuga'       # Your project key in SonarCloud
    cliProjectName: 'DevOps-Group4'      # Your project name in SonarCloud

# Step 2: Maven Build + Test
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '21'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'clean verify'

# Step 3: SonarCloud Analyze
- task: SonarCloudAnalyze@1

# Step 4: SonarCloud Publish Quality Gate
- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'

# Step 5: Publish build artifacts (optional but recommended)
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(System.DefaultWorkingDirectory)/target'
    ArtifactName: 'drop'
    publishLocation: 'Container'
