trigger:
- master

pool:
  name: AgentDonalda

variables:
  buildConfiguration: 'Release'
  JAVA_HOME: 'C:\Program Files\Java\jdk-21'
  jarFileName: 'DevOps-Group4-1.0-SNAPSHOT.jar'  # <-- UPDATE this if your actual JAR name is different

stages:
# ------------------------------
# CI - BUILD & TEST
# ------------------------------
- stage: Build
  displayName: 'Build and Test'
  jobs:
    - job: Build
      steps:
        - checkout: self

        - task: Maven@3
          inputs:
            mavenPomFile: 'pom.xml'
            goals: 'clean install'
            options: '-DskipTests=false'
            javaHomeOption: 'UserPath'
            jdkVersionOption: '21'
            mavenVersionOption: 'Default'
            publishJUnitResults: true
            testResultsFiles: '**/surefire-reports/TEST-*.xml'
            jdkDirectory: $(JAVA_HOME)

        - script: echo $(JAVA_HOME)
          displayName: 'Check JAVA_HOME'

        - script: dir "$(System.DefaultWorkingDirectory)\target" /s
          displayName: 'Debug target directory after Maven build'

        - task: SonarCloudPrepare@1
          inputs:
            SonarCloud: 'DevOps'
            organization: 'donaldazhuga'
            scannerMode: 'CLI'
            configMode: 'manual'
            cliProjectKey: 'donaldazhuga'
            cliProjectName: 'DevOps-Group4'
            cliSources: '.'

        - task: SonarCloudPublish@1
          inputs:
            pollingTimeoutSec: '300'

        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: 'target'
            ArtifactName: 'drop'
            publishLocation: 'Container'

# ------------------------------
# CD - DELIVER ARTIFACTS
# ------------------------------
- stage: Deliver
  displayName: 'Deliver Artifacts'
  dependsOn: Build
  jobs:
    - job: Deliver
      steps:
        - download: current
          artifact: drop

        - script: dir "$(System.DefaultWorkingDirectory)\drop" /s
          displayName: 'Verify downloaded artifact contents'

        - script: echo "Delivering artifact to the next stage"
          displayName: 'Mock Deliver Step'

# ------------------------------
# CD - DEPLOY TO DEV
# ------------------------------
- stage: DeployToDev
  displayName: 'Deploy to Dev Environment'
  dependsOn: Deliver
  jobs:
    - job: DeployDev
      steps:
        - script: dir "$(System.DefaultWorkingDirectory)\drop" /s
          displayName: 'List files in drop directory'

        - script: |
            echo "Starting deployment to Dev Environment on port 8081"
            java -jar "$(System.DefaultWorkingDirectory)\drop\$(jarFileName)" --server.port=8081
          displayName: 'Deploy to Dev Port 8081'

# ------------------------------
# CD - DEPLOY TO QAT
# ------------------------------
- stage: DeployToQAT
  displayName: 'Deploy to QAT Environment'
  dependsOn: DeployToDev
  jobs:
    - job: DeployQAT
      steps:
        - script: echo "Mock deployment to QAT Environment"
          displayName: 'Deploy to QAT'

# ------------------------------
# CD - DEPLOY TO STAGING
# ------------------------------
- stage: DeployToStaging
  displayName: 'Deploy to Staging Environment'
  dependsOn: DeployToQAT
  jobs:
    - job: DeployStaging
      steps:
        - script: echo "Mock deployment to Staging Environment"
          displayName: 'Deploy to Staging'

# ------------------------------
# CD - DEPLOY TO PRODUCTION
# ------------------------------
- stage: DeployToProduction
  displayName: 'Deploy to Production Environment'
  dependsOn: DeployToStaging
  jobs:
    - job: DeployProd
      steps:
        - script: echo "Mock deployment to Production Environment"
          displayName: 'Deploy to Production'
