trigger:
- master

pool:
  name: AgentDonalda

variables:
  SONAR_TOKEN: $(SONAR_TOKEN)  # Make sure this is securely set in Azure DevOps Pipeline UI

steps:
# Step 1: SonarCloud Prepare
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'DevOps'                   # Name of your Azure DevOps SonarCloud service connection
    organization: 'donaldazhuga'           # Your organization ID in SonarCloud
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: 'devops-group4'         # Your actual project key in SonarCloud
    cliProjectName: 'DevOps-Group4'        # Your SonarCloud project name
    extraProperties: |
      sonar.login=$(SONAR_TOKEN)

# Step 2: Maven Build + Test
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '21'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'clean verify'

# Step 3: SonarCloud Analyze
- task: SonarCloudAnalyze@1
  inputs:
    extraProperties: |
      sonar.verbose=true
      sonar.java.source=21
      sonar.java.target=21
      sonar.login=$(SONAR_TOKEN)

# Step 4: SonarCloud Publish Quality Gate
- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'

# Step 5: Publish Build Artifacts
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(System.DefaultWorkingDirectory)/target'
    ArtifactName: 'drop'
    publishLocation: 'Container'
